name: Deploy Logic App

on:
  push:
    paths:
      - 'modules/logicapp.bicep'
    branches:
      - main

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Logic App
        run: |
          az deployment group create \
            --resource-group rg-cosmos-learning \
            --template-file modules/logicapp.bicep